import { Box, Stack, Typography } from "@mui/material";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "BKCycling",
  description: "Generated by Cycling",
};

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="flex w-full h-screen flex-row">
      <div className="flex-1 h-screen">{children}</div>
      <div className="bg-[#836FFF] flex-1">
        <Box
          sx={{
            backgroundColor: "#836FFF",
            color: "var(--mui-palette-common-white)",
            display: "flex",
            flexDirection: "column",
            justifyContent: "center",
            alignItems: "center",
            height: "100%",
            paddingBottom: "120px",
          }}
        >
          <Stack spacing={3}>
            <Stack spacing={2}>
              <Typography
                color="inherit"
                sx={{
                  fontSize: "30px",
                  lineHeight: "32px",
                  textAlign: "center",
                }}
                variant="h1"
              >
                Welcome to{" "}
                <Box component="span" sx={{ color: "#FABF0C" }}>
                  Cycling
                </Box>
              </Typography>
              <Typography align="center" variant="subtitle1">
                A professional template that comes with ready-to-use MUI
                components.
              </Typography>
            </Stack>
            <Box sx={{ display: "flex", justifyContent: "center" }}>
              <Box
                component="img"
                alt="Widgets"
                src="/assets/login.jpg"
                sx={{
                  height: "auto",
                  width: "100%",
                  maxWidth: "600px",
                  borderRadius: 4,
                }}
              />
            </Box>
          </Stack>
        </Box>
      </div>
    </div>
  );
}
