import Header from "@/components/header";
import Sidebar from "@/components/sidebar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "BKCycling",
  description: "Generated by Cycling",
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="flex w-full h-screen">
      <div className="w-1/6 bg-slate-900 ">
        <Sidebar />
      </div>
      <div className="w-5/6 bg-slate-100 flex flex-col">
        <Header />
        <div className="overflow-auto">{children}</div>
      </div>
    </div>
  );
}
